USE [master]
GO

/****** Object:  Database [HubCountDatabase]    Script Date: 12/02/2021 17:54:28 ******/
CREATE DATABASE [HubCountDatabase]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'HubCountDatabase', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\HubCountDatabase.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'HubCountDatabase_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\HubCountDatabase_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [HubCountDatabase].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [HubCountDatabase] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [HubCountDatabase] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [HubCountDatabase] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [HubCountDatabase] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [HubCountDatabase] SET ARITHABORT OFF 
GO

ALTER DATABASE [HubCountDatabase] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [HubCountDatabase] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [HubCountDatabase] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [HubCountDatabase] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [HubCountDatabase] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [HubCountDatabase] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [HubCountDatabase] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [HubCountDatabase] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [HubCountDatabase] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [HubCountDatabase] SET  DISABLE_BROKER 
GO

ALTER DATABASE [HubCountDatabase] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [HubCountDatabase] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [HubCountDatabase] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [HubCountDatabase] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [HubCountDatabase] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [HubCountDatabase] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [HubCountDatabase] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [HubCountDatabase] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [HubCountDatabase] SET  MULTI_USER 
GO

ALTER DATABASE [HubCountDatabase] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [HubCountDatabase] SET DB_CHAINING OFF 
GO

ALTER DATABASE [HubCountDatabase] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [HubCountDatabase] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [HubCountDatabase] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [HubCountDatabase] SET QUERY_STORE = OFF
GO

ALTER DATABASE [HubCountDatabase] SET  READ_WRITE 
GO


